var RYPP=(function($,undefined){'use strict';function Rypp(el,api_key,options){if(typeof api_key==='undefined'){console.log("Youtube API V3 requires a valid API KEY.\nFollow the instructions at: https://developers.google.com/youtube/v3/getting-started");return false;}
this.DOM={};this.options={};this.data={ytapi:{playlist_info:'https://www.googleapis.com/youtube/v3/playlists?part=snippet&id={{RESOURCES_ID}}&key={{YOUR_API_KEY}}',playlist:'https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&maxResults=50&playlistId={{RESOURCES_ID}}&key={{YOUR_API_KEY}}',videolist:'https://www.googleapis.com/youtube/v3/videos?part=snippet,status&maxResults=50&id={{RESOURCES_ID}}&key={{YOUR_API_KEY}}'},firsttime:true,ismobile:(typeof window.orientation!=='undefined')};this.init(el,api_key,options);}
Rypp.prototype={init:function(el,api_key,options){this.api_key=api_key;this.options={update_title_desc:false,autoplay:true,autonext:true,loop:true,mute:false};if(typeof options!=='undefined'){$.extend(this.options,options);}
this.ytplayer=null;this.DOM={};this.DOM.$el=$(el);this.DOM.$playlc=this.DOM.$el.find('.RYPP-playlist');this.DOM.$items=this.DOM.$el.find('.RYPP-items');this.DOM.$videoc=this.DOM.$el.find('.RYPP-video');this.DOM.$title=this.DOM.$el.find('.RYPP-title');this.DOM.$desc=this.DOM.$el.find('.RYPP-desc');this.data.player_uid=(Math.random().toString(16).substr(2,8));this.DOM.$el.attr('data-rypp',this.data.player_uid).find('.RYPP-video-player').attr('id','RYPP-vp-'+this.data.player_uid);if(typeof YT==='undefined'){var
tag=document.createElement('script'),hID=document.getElementsByTagName('head')[0];tag.src='https://www.youtube.com/player_api';hID.appendChild(tag);}},onYouTubeIframeAPIReady:function(){if(this.options.update_title_desc){this.updateTitleDesc();}
this.populatePlaylist();},updateTitleDesc:function(){var
that=this,resources_id=this.DOM.$el.attr('data-playlist'),url=this.data.ytapi.playlist_info.replace('{{RESOURCES_ID}}',resources_id).replace('{{YOUR_API_KEY}}',this.api_key);$.ajaxSetup({cache:false});$.ajax(url,{context:this,dataType:'json',crossDomain:true,error:function(){},success:function(data){this.DOM.$title.html(data.items[0].snippet.title);this.DOM.$desc.html(data.items[0].snippet.description);}});},populatePlaylist:function(){this.DOM.$items.html('').append($('<ol>'));if(this.DOM.$el.attr('data-playlist')){this.getVideosFrom('playlist',this.DOM.$el.attr('data-playlist'));}else if(this.DOM.$el.attr('data-ids')){var vl=this.DOM.$el.attr('data-ids');vl=($.map(vl.split(','),$.trim)).join(',');this.getVideosFrom('videolist',vl);}},addAPIPlayer:function(){var that=this;this.ytplayer=new YT.Player('RYPP-vp-'+this.data.player_uid,{playerVars:{enablejsapi:1,rel:0,modestbranding:1,wmode:'transparent'},events:{'onReady':function(){that.onPlayerReady();},'onStateChange':function(e){that.onPlayerStateChange(e);},'onError':function(e){console.log(e);}}});},onPlayerReady:function(){this.startPlayList();},onPlayerStateChange:function(e){var
that=this;if(typeof e!=='undefined'){if(e.data===-1&&this.data.firsttime){if(!this.options.autoplay&&!this.data.ismobile){this.ytplayer.stopVideo();this.data.firsttime=false;}
if(this.options.mute){this.ytplayer.mute();}}
if(e.data===3&&this.data.ismobile&&this.data.firsttime){setTimeout(function(){that.ytplayer.stopVideo();that.data.firsttime=false;},500);}
var next=null;if(e.data===0&&!this.data.ismobile&&this.options.autonext){next=this.DOM.$items.find('li.selected').next();if(next.length===0&&this.options.loop){next=this.DOM.$items.find('li').first();}
next.click();}}},getVideosFrom:function(kind,resources_id){var
that=this,url=this.data.ytapi[kind].replace('{{RESOURCES_ID}}',resources_id).replace('{{YOUR_API_KEY}}',this.api_key);$.ajaxSetup({cache:false});$.ajax(url,{context:this,dataType:'json',crossDomain:true,error:function(){},success:function(data){if(data.kind==='youtube#playlistItemListResponse'){var vl=$.map(data.items,function(val,idx){if(typeof val.snippet.resourceId.videoId!=='undefined'){return val.snippet.resourceId.videoId;}}).join(',');that.getVideosFrom('videolist',vl);}else if(data.kind==='youtube#videoListResponse'){for(var i=0,len=data.items.length;i<len;i++){var item=data.items[i];if($.inArray(item.status.uploadStatus,['rejected','deleted','failed'])===-1&&typeof item.snippet.thumbnails!=='undefined'){var
vid=item.id,tit=item.snippet.title,aut=item.snippet.channelTitle,thu=item.snippet.thumbnails.default.url;that.addVideo2Playlist(vid,tit,aut,thu);}}
that.addAPIPlayer();}}});},startPlayList:function(){var
D=this.DOM,vid=null,that=this;D.$items.on('click','li',function(e){e.preventDefault();D.$items.find('li').removeClass('selected');$(this).addClass('selected');vid=$(this).data('video-id');that.ytplayer.loadVideoById(vid);if(that.data.ismobile){that.data.firsttime=true;}});if(D.$items.find('li.selected').length===0){D.$items.find('li').first().click();}},addVideo2Playlist:function(vid,tit,aut,thu){var
D=this.DOM;$('<li data-video-id="'+vid+'"><p class="title">'+tit+'<small class="author"><br>'+aut+'</small></p><img src="'+thu+'" class="thumb"></li>').appendTo(D.$items.find('ol'));},};return Rypp;}(jQuery));function onYouTubeIframeAPIReady(){$('[data-rypp]').each(function(idx,el){$(el)[0].rypp_data_obj.onYouTubeIframeAPIReady();});}
$.fn.rypp=function(api_key,options){return this.each(function(){this.rypp_data_obj=new RYPP(this,api_key,options);});};